### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Hmm, actually, should we update this as breaking changes?

**Comment by trontrytel** [comment]
I don't think so. The change between Lv0 and Lv(T)  should not be that big for our purposes

**Comment by charleskawczynski** [comment]
Fine by me, just note that it might break TC.jl's CI since it's so sensitive, but we can just open a PR that updates the MSE tables

**Pull request merged**
