### PR TITLE
(Try 2) Improve the explanation surrounding "virtual temperature" and a hypothetical "density temperature"

### PR DESCRIPTION
**Pull request by glwagner**
Supercedes #171, trying again now that I have contributor privileges.

From #171:

I thought the description could be improved by being a little more explicit. If I've made a mistake, let me know and I can fix it. I also embellished the "side point" by putting it in a box to emphasize that this is additional information that isn't core to understanding the main thread.

### CODE REVIEW

**Comment by glwagner** [comment]
@charleskawczynski looks like buildkite won't run for this either

**Comment by charleskawczynski** [comment]
@glwagner, we have a label to launch buildkite in thermodynamics, looks like it's started now 🎉

**Review by charleskawczynski — APPROVED** [review]
Changes look fine to me.

**Comment by glwagner** [comment]
> @glwagner, we have a label to launch buildkite in thermodynamics, looks like it's started now 🎉

got it

**Comment by charleskawczynski** [comment]
I'll go ahead and rebase this PR @glwagner

**Comment by charleskawczynski** [comment]
I think we were experimenting with the buildkite settings, and CI was not working because of that. Hopefully things should be smooth moving forward.

**Pull request merged**
